custom:
  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      group-id: group_id
      topic:
        offline:
          name: offline
        online:
          name: online
  url:
    validation: http://localhost:9000/payment
    log: http://localhost:9000/log

server:
  port: 5000

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/payments
    username: tech
    password: test
